export const CLOUD = "cloud";
export const CLOUDY = "cloudy";
export const SUN = "sunny";
export const RAIN = "rain"
export const SNOW ="snow"
export const WINDY ="windy"
export const THUNDERSTORM = "thurnderstorm"
export const THUNDER = "thunder"
export const DRIZZLE = "drizzle"